service: test-actions-repo

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    blockPublicAccess: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
