name: Auto Merge Branch
on:
  push:
    branches:
      - temp2
      - dev

jobs:
  # When pushing to temp2, immediately merge temp2 -> uat
  auto_merge_temp2_to_uat:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/temp2'
    steps:
      - uses: actions/checkout@v4
      - name: Merge temp2 -> uat
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: temp2
          target_branch: uat
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  # When pushing to dev, back-merge dev into feature branches (f1..f9)
  auto_back_merge_dev_to_features:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref == 'refs/heads/dev'
    strategy:
      matrix:
        target: [f1, f2, f3, f4, f5, f6, f7, f8, f9]
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> ${{ matrix.target }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: ${{ matrix.target }}
          message: Merge dev into ${{ matrix.target }}
          github_token: ${{ secrets.GH_AUTO_MERGER }}
